version: "3.7"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wisely_test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/wisely_test?user=postgres&password=password
      - APP_ENV=development
      - PORT=8080
      - LOG=debug
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:8080"
