name: Build

on:
  push:
    branches: ['master']
    paths-ignore: ['**.md']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - name: Build
        run: ./gradlew build

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: build/reports/tests/test
